# Generated by Django 4.0.4 on 2022-04-19 15:45

from django.conf import settings
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_remove_profile_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=models.SET(pages.models.get_deleted_user), related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=models.SET(pages.models.get_deleted_user), related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
